baseurl         = "https://hamburg.stefanimhoff.de/"
title           = "Exploring Hamburg"
languageCode    = "de"

metaDataFormat  = "yaml"
paginate        = 0
buildDrafts     = true
buildFuture     = true
disableKinds    = ["404"]
enableRobotsTXT = true
watch           = true

archetypedir  = "app/archetypes"
contentdir    = "app/content"
dataDir       = "app/data"
layoutdir     = "app/layouts"
staticdir     = "app/static"
themesdir     = "app/themes"
publishdir    = "dist"

[blackfriday]
  smartypants     = false
  plainIDAnchors  = true
  hrefTargetBlank = true
  extensions      = [""]

[permalinks]
  stadtteil = "/:slug/"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Startseite"
  url = "/"
  weight = 0
[[menu.main]]
  name = "Impressum"
  url = "/impressum/"
  weight = 10

[params]
  criticalcss = false
  tracking    = false
  description = "Hamburg entdecken. Straße für Straße, Stadtteil für Stadtteil."
  feedburner = "https://feeds.feedburner.com/hamburg-stefanimhoff"
